# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/postrick/Documents/Uni/2/H62PEP/ModelLoader

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/postrick/Documents/Uni/2/H62PEP/ModelLoader

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/postrick/Documents/Uni/2/H62PEP/ModelLoader/CMakeFiles /home/postrick/Documents/Uni/2/H62PEP/ModelLoader/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/postrick/Documents/Uni/2/H62PEP/ModelLoader/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ModelLoader

# Build rule for target.
ModelLoader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ModelLoader
.PHONY : ModelLoader

# fast build rule for target.
ModelLoader/fast:
	$(MAKE) -f CMakeFiles/ModelLoader.dir/build.make CMakeFiles/ModelLoader.dir/build
.PHONY : ModelLoader/fast

src/cell.o: src/cell.cpp.o

.PHONY : src/cell.o

# target to build an object file
src/cell.cpp.o:
	$(MAKE) -f CMakeFiles/ModelLoader.dir/build.make CMakeFiles/ModelLoader.dir/src/cell.cpp.o
.PHONY : src/cell.cpp.o

src/cell.i: src/cell.cpp.i

.PHONY : src/cell.i

# target to preprocess a source file
src/cell.cpp.i:
	$(MAKE) -f CMakeFiles/ModelLoader.dir/build.make CMakeFiles/ModelLoader.dir/src/cell.cpp.i
.PHONY : src/cell.cpp.i

src/cell.s: src/cell.cpp.s

.PHONY : src/cell.s

# target to generate assembly for a file
src/cell.cpp.s:
	$(MAKE) -f CMakeFiles/ModelLoader.dir/build.make CMakeFiles/ModelLoader.dir/src/cell.cpp.s
.PHONY : src/cell.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/ModelLoader.dir/build.make CMakeFiles/ModelLoader.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/ModelLoader.dir/build.make CMakeFiles/ModelLoader.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/ModelLoader.dir/build.make CMakeFiles/ModelLoader.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/material.o: src/material.cpp.o

.PHONY : src/material.o

# target to build an object file
src/material.cpp.o:
	$(MAKE) -f CMakeFiles/ModelLoader.dir/build.make CMakeFiles/ModelLoader.dir/src/material.cpp.o
.PHONY : src/material.cpp.o

src/material.i: src/material.cpp.i

.PHONY : src/material.i

# target to preprocess a source file
src/material.cpp.i:
	$(MAKE) -f CMakeFiles/ModelLoader.dir/build.make CMakeFiles/ModelLoader.dir/src/material.cpp.i
.PHONY : src/material.cpp.i

src/material.s: src/material.cpp.s

.PHONY : src/material.s

# target to generate assembly for a file
src/material.cpp.s:
	$(MAKE) -f CMakeFiles/ModelLoader.dir/build.make CMakeFiles/ModelLoader.dir/src/material.cpp.s
.PHONY : src/material.cpp.s

src/matrix.o: src/matrix.cpp.o

.PHONY : src/matrix.o

# target to build an object file
src/matrix.cpp.o:
	$(MAKE) -f CMakeFiles/ModelLoader.dir/build.make CMakeFiles/ModelLoader.dir/src/matrix.cpp.o
.PHONY : src/matrix.cpp.o

src/matrix.i: src/matrix.cpp.i

.PHONY : src/matrix.i

# target to preprocess a source file
src/matrix.cpp.i:
	$(MAKE) -f CMakeFiles/ModelLoader.dir/build.make CMakeFiles/ModelLoader.dir/src/matrix.cpp.i
.PHONY : src/matrix.cpp.i

src/matrix.s: src/matrix.cpp.s

.PHONY : src/matrix.s

# target to generate assembly for a file
src/matrix.cpp.s:
	$(MAKE) -f CMakeFiles/ModelLoader.dir/build.make CMakeFiles/ModelLoader.dir/src/matrix.cpp.s
.PHONY : src/matrix.cpp.s

src/model.o: src/model.cpp.o

.PHONY : src/model.o

# target to build an object file
src/model.cpp.o:
	$(MAKE) -f CMakeFiles/ModelLoader.dir/build.make CMakeFiles/ModelLoader.dir/src/model.cpp.o
.PHONY : src/model.cpp.o

src/model.i: src/model.cpp.i

.PHONY : src/model.i

# target to preprocess a source file
src/model.cpp.i:
	$(MAKE) -f CMakeFiles/ModelLoader.dir/build.make CMakeFiles/ModelLoader.dir/src/model.cpp.i
.PHONY : src/model.cpp.i

src/model.s: src/model.cpp.s

.PHONY : src/model.s

# target to generate assembly for a file
src/model.cpp.s:
	$(MAKE) -f CMakeFiles/ModelLoader.dir/build.make CMakeFiles/ModelLoader.dir/src/model.cpp.s
.PHONY : src/model.cpp.s

src/vector3d.o: src/vector3d.cpp.o

.PHONY : src/vector3d.o

# target to build an object file
src/vector3d.cpp.o:
	$(MAKE) -f CMakeFiles/ModelLoader.dir/build.make CMakeFiles/ModelLoader.dir/src/vector3d.cpp.o
.PHONY : src/vector3d.cpp.o

src/vector3d.i: src/vector3d.cpp.i

.PHONY : src/vector3d.i

# target to preprocess a source file
src/vector3d.cpp.i:
	$(MAKE) -f CMakeFiles/ModelLoader.dir/build.make CMakeFiles/ModelLoader.dir/src/vector3d.cpp.i
.PHONY : src/vector3d.cpp.i

src/vector3d.s: src/vector3d.cpp.s

.PHONY : src/vector3d.s

# target to generate assembly for a file
src/vector3d.cpp.s:
	$(MAKE) -f CMakeFiles/ModelLoader.dir/build.make CMakeFiles/ModelLoader.dir/src/vector3d.cpp.s
.PHONY : src/vector3d.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... ModelLoader"
	@echo "... edit_cache"
	@echo "... src/cell.o"
	@echo "... src/cell.i"
	@echo "... src/cell.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/material.o"
	@echo "... src/material.i"
	@echo "... src/material.s"
	@echo "... src/matrix.o"
	@echo "... src/matrix.i"
	@echo "... src/matrix.s"
	@echo "... src/model.o"
	@echo "... src/model.i"
	@echo "... src/model.s"
	@echo "... src/vector3d.o"
	@echo "... src/vector3d.i"
	@echo "... src/vector3d.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

